Fix build for SPM generated Xcode project
robbiehanson/CocoaAsyncSocket pull request #732
Opened 2020-09-07 22:22 UTC by wlisac

## Overview
This fixes the issue described in https://github.com/robbiehanson/CocoaAsyncSocket/issues/727.

Before this change, the Xcode project generated by the Swift Package Manager failed to build.

```zsh
% swift package generate-xcodeproj --output spm-generated.xcodeproj
% xcodebuild -project spm-generated.xcodeproj
```

The generated project failed to build because `CLANG_ENABLE_MODULES` was set to `NO`.

We can have the generated project set `CLANG_ENABLE_MODULES` to `YES` by [including the umbrella header](https://bugs.swift.org/browse/SR-7531?focusedCommentId=36686&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-36686) in the `publicHeadersPath`.

Thanks for considering these changes and for supporting this library.

– Will

cc @RockLobster for any input since this is a follow on to https://github.com/robbiehanson/CocoaAsyncSocket/pull/706.

## Detailed Changes
- Move umbrella header so that it’s included in the package’s `publicHeadersPath`
    - `Source/CocoaAsyncSocket.h` → `Source/GCD/CocoaAsyncSocket.h`
- Use local imports for umbrella header to fix `swift test` after moving the umbrella header

See [AFNetworking](https://github.com/AFNetworking/AFNetworking) for a similar [folder structure](https://github.com/AFNetworking/AFNetworking/tree/master/AFNetworking), [umbrella header format](https://github.com/AFNetworking/AFNetworking/blob/master/AFNetworking/AFNetworking.h), and [`publicHeadersPath` configuration](https://github.com/AFNetworking/AFNetworking/blob/master/Package.swift#L37)

## Tests
- Updated Travis to test SPM's generated Xcode project
- Manually tested these changes are compatible with CocoaPods and Carthage
- [All automated tests are passing](https://travis-ci.com/github/wlisac/CocoaAsyncSocket/builds/183027326)

2020-09-10 08:33 UTC, RockLobster commented
Changes look good to me!

Was surprised that if you just open the Package.swift in xcode (xcode has built-in support by now), 
then the generated project can be built and tested without issues.

But when running `swift package generate-xcodeproj`, then the generated project can't be built.

2020-09-13 16:58 UTC, wlisac commented
Thanks for the review, @RockLobster – I was surprised, too.

@chrisballinger is this something you'd consider merging and tagging a release for?

I'm hoping to open a PR in https://github.com/emqx/CocoaMQTT that adopts this change before their 1.3.0 release.

2020-12-06 04:38 UTC, 510sss approved these changes

2021-01-24 19:34 UTC, chrisballinger requested changes
Please revert changes to `CocoaAsyncSocket.h` as described. Thanks!

2021-01-24 19:35 UTC, chrisballinger requested changes
Please revert changes to `CocoaAsyncSocket.h` as described. Thanks!

2021-01-24 19:35 UTC, chrisballinger commented on Source/GCD/CocoaAsyncSocket.h
> +#endif
1) ifndef/define guards are not needed with import statements: https://stackoverflow.com/a/439691
2) Xcode 12 will warn against this change: 'Double-quoted include in framework header, expected angle-bracketed instead'

2021-02-18 10:00 UTC, Ast3r10n commented
Is this still alive? It would really help.

2021-04-28 00:17 UTC, closed without merging